# Generated by Django 6.0.1 on 2026-02-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scenario_type', models.CharField(choices=[('startup', 'Reactor Startup'), ('shutdown', 'Emergency Shutdown'), ('transient', 'Power Transient'), ('failure', 'Equipment Failure'), ('safety', 'Safety Procedure')], max_length=50)),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('initial_conditions', models.JSONField(default=dict)),
                ('learning_objectives', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('year_of_study', models.IntegerField(default=1)),
                ('total_training_hours', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('safety_rating', models.FloatField(default=0.0)),
                ('efficiency_rating', models.FloatField(default=0.0)),
                ('achievements', models.JSONField(default=list)),
                ('completed_scenarios', models.ManyToManyField(blank=True, to='simulator.simulationscenario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('reactor_state', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('safety_violations', models.IntegerField(default=0)),
                ('efficiency_score', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.simulationscenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback_type', models.CharField(choices=[('warning', '⚠️ Warning'), ('suggestion', '💡 Suggestion'), ('praise', '✅ Praise'), ('critical', '🚨 Critical'), ('educational', '📚 Educational')], max_length=50)),
                ('message', models.TextField()),
                ('reactor_state', models.JSONField(default=dict)),
                ('trigger_action', models.CharField(blank=True, max_length=200)),
                ('trigger_parameter', models.CharField(blank=True, max_length=100)),
                ('trigger_value', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.trainingsession')),
            ],
        ),
    ]
