# Generated by Django 6.0.1 on 2026-02-03 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('achievement_type', models.CharField(choices=[('course', 'Course Completion'), ('scenario', 'Scenario Mastery'), ('skill', 'Skill Development'), ('milestone', 'Milestone Reached'), ('challenge', 'Special Challenge'), ('participation', 'Participation')], max_length=50)),
                ('description', models.TextField()),
                ('requirement_type', models.CharField(choices=[('score', 'Minimum Score'), ('count', 'Number of Completions'), ('time', 'Time Requirement'), ('combination', 'Combination')], max_length=50)),
                ('requirement_value', models.JSONField(default=dict)),
                ('icon_class', models.CharField(default='fas fa-trophy', max_length=50)),
                ('badge_color', models.CharField(default='#FFD700', max_length=7)),
                ('xp_reward', models.IntegerField(default=100)),
                ('unlocks_feature', models.CharField(blank=True, max_length=100)),
                ('total_earned', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['achievement_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assignment_type', models.CharField(choices=[('simulation', 'Simulation Exercise'), ('theory', 'Theory Assignment'), ('report', 'Lab Report'), ('project', 'Project Work'), ('quiz', 'Online Quiz'), ('presentation', 'Presentation')], default='simulation', max_length=50)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('max_score', models.FloatField(default=100.0)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('late_penalty', models.FloatField(default=0.0)),
                ('allow_multiple_attempts', models.BooleanField(default=False)),
                ('max_attempts', models.IntegerField(default=1)),
                ('submission_format', models.CharField(blank=True, default='Training Session', max_length=100)),
                ('attached_files', models.JSONField(blank=True, default=list)),
                ('reference_materials', models.TextField(blank=True)),
                ('total_submissions', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_submission', models.TextField(blank=True)),
                ('attached_files', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned for Revision'), ('late', 'Late Submission')], default='draft', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_possible_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('rubric_scores', models.JSONField(blank=True, default=dict)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('needs_revision', models.BooleanField(default=False)),
                ('revision_notes', models.TextField(blank=True)),
                ('resubmitted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('duration_hours', models.IntegerField(default=10)),
                ('credits', models.IntegerField(default=3)),
                ('is_published', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('syllabus', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('color_code', models.CharField(default='#1a237e', max_length=7)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('pass_score', models.FloatField(default=70.0)),
                ('estimated_time', models.IntegerField(default=30)),
                ('learning_points', models.TextField(blank=True)),
                ('difficulty_multiplier', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('estimated_duration', models.IntegerField(default=40)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('recommended_by_ai', models.BooleanField(default=False)),
                ('ai_reasoning', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('target_score', models.FloatField(default=70.0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('target_score', models.FloatField(default=70.0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='aifeedback',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='simulationscenario',
            options={'ordering': ['difficulty', 'name']},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-average_score']},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.RenameField(
            model_name='trainingsession',
            old_name='reactor_state',
            new_name='final_state',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='completed_scenarios',
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='category',
            field=models.CharField(choices=[('safety', 'Safety'), ('operation', 'Operation'), ('theory', 'Theory'), ('efficiency', 'Efficiency'), ('technique', 'Technique')], default='safety', max_length=50),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='concept_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='implementation_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='learning_objective',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='student_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='was_implemented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='average_completion_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='expected_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='icon_class',
            field=models.CharField(default='fas fa-reactor', max_length=50),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='simulator.simulationscenario'),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='reactor_model',
            field=models.CharField(default='VVER-1200', max_length=100),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='reference_docs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='safety_focus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='theory_material',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='scenario_thumbnails/'),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='video_tutorial',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='completed_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learning_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learning_style',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('rapid_experimental', 'Rapid Experimental'), ('deliberate_calculative', 'Deliberate Calculative'), ('visual', 'Visual Learner'), ('auditory', 'Auditory Learner'), ('kinesthetic', 'Kinesthetic Learner')], default='balanced', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='action_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='action_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='ai_feedback_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='checkpoint_saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='control_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='critical_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='duration_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='feedback_implemented',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='initial_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='max_pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='max_temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='power_stability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='reaction_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='session_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='state_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='feedback_type',
            field=models.CharField(choices=[('warning', '⚠️ Warning'), ('suggestion', '💡 Suggestion'), ('praise', '✅ Praise'), ('critical', '🚨 Critical'), ('educational', '📚 Educational'), ('safety', '🛡️ Safety Tip'), ('efficiency', '⚡ Efficiency Tip'), ('theory', '🧪 Theory Explanation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_messages', to='simulator.trainingsession'),
        ),
        migrations.AlterField(
            model_name='simulationscenario',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], default=1),
        ),
        migrations.AlterField(
            model_name='simulationscenario',
            name='scenario_type',
            field=models.CharField(choices=[('startup', 'Reactor Startup'), ('shutdown', 'Emergency Shutdown'), ('transient', 'Power Transient'), ('failure', 'Equipment Failure'), ('safety', 'Safety Procedure'), ('maintenance', 'Maintenance Operation'), ('inspection', 'Safety Inspection'), ('emergency', 'Emergency Response')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(blank=True, default='Nuclear Engineering', max_length=200),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['session', 'feedback_type'], name='simulator_a_session_be1158_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['category', 'priority'], name='simulator_a_categor_03b3cb_idx'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='prerequisite_achievements',
            field=models.ManyToManyField(blank=True, to='simulator.achievement'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='simulator.simulationscenario'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='simulator.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_submissions', to='simulator.trainingsession'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='assignment_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='simulator.assignmentsubmission'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'start_time'], name='simulator_t_user_id_77c484_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['scenario', 'score'], name='simulator_t_scenari_643827_idx'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='simulator.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='simulator.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='simulator.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursescenario',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_scenarios', to='simulator.course'),
        ),
        migrations.AddField(
            model_name='coursescenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.simulationscenario'),
        ),
        migrations.AddField(
            model_name='simulationscenario',
            name='courses',
            field=models.ManyToManyField(related_name='scenarios', through='simulator.CourseScenario', to='simulator.course'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningpathcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.course'),
        ),
        migrations.AddField(
            model_name='learningpathcourse',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.learningpath'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='courses',
            field=models.ManyToManyField(through='simulator.LearningPathCourse', to='simulator.course'),
        ),
        migrations.AddField(
            model_name='learningpathscenario',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.learningpath'),
        ),
        migrations.AddField(
            model_name='learningpathscenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.simulationscenario'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='scenarios',
            field=models.ManyToManyField(through='simulator.LearningPathScenario', to='simulator.simulationscenario'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'due_date'], name='simulator_a_course__2a36cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='coursescenario',
            unique_together={('course', 'scenario')},
        ),
        migrations.AlterUniqueTogether(
            name='learningpathcourse',
            unique_together={('learning_path', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='learningpathscenario',
            unique_together={('learning_path', 'scenario')},
        ),
    ]
